version: "3"

volumes:
  python_sock:
  # nginx_logs:

services:
  # nginx:
  #   restart: unless-stopped
  #   image: nginx:alpine
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./backend/static:/var/www/backend/static
  #     - ./backend/media:/var/www/backend/media
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
  #     - nginx_logs:/var/log/nginx
  #     - python_sock:/var/run/python

  backend:
    restart: unless-stopped
    image: django/binance
    build:
      context: ./docker/backend
    volumes:
      - ./backend:/var/www/backend
      - python_sock:/var/run/python
